Document: cue2tracks
Title: Debian cue2tracks Manual
Author: <insert document author here>
Abstract: This manual describes what cue2tracks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cue2tracks/cue2tracks.sgml.gz

Format: postscript
Files: /usr/share/doc/cue2tracks/cue2tracks.ps.gz

Format: text
Files: /usr/share/doc/cue2tracks/cue2tracks.text.gz

Format: HTML
Index: /usr/share/doc/cue2tracks/html/index.html
Files: /usr/share/doc/cue2tracks/html/*.html
